version: "3.1"
services:
    mariadb:
      image: mariadb:latest
      container_name: prestashop-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=prestashop
        - MYSQL_USER=prestashop
        - MYSQL_PASSWORD=prestashop
      ports:
        - "8155:3306"

    webserver:
      image: nginx:stable
      container_name: prestashop-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./engine/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8055:80"

    php-fpm:
      build:
        context: engine/php-fpm
      container_name: prestashop-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./engine/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: prestashop-phpmyadmin
      links:
        - mariadb:db
      ports:
        - "80:80"
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root

    nodejs:
      build: engine/nodejs
      container_name: prestashop-nodejs
      working_dir: /application
      volumes:
        - .:/application
      tty: true
